import os
import time
from termcolor import colored,cprint

os.system('cls')
print(colored("3...","yellow"))
time.sleep(1)
os.system('cls')
print(colored("2...","yellow"))
time.sleep(2)
os.system('cls')
print(colored("1...","yellow"))
time.sleep(2)
os.system('cls')
cprint("\t\t\t\t\t\t\t  =======SELAMAT DATANG DI PROGRAM PEMBUATAN LOGO ADIDAS=======  ","blue","on_white")
time.sleep(2)
print()
def logo_adidas():
    print(colored("\t\t\t\t\t\t\t\t                                                   ", "black","on_white"))
    print(colored("\t\t\t\t\t\t\t\t                                                   ", "black","on_white"))
    print(colored("\t\t\t\t\t\t\t\t    ███                 ██                  ███    ", "black","on_white"))
    time.sleep(1)
    print(colored("\t\t\t\t\t\t\t\t   ███████             ████             ███████    ", "black","on_white"))
    time.sleep(1)
    print(colored("\t\t\t\t\t\t\t\t  ████████████       ████████       ████████████   ", "black","on_white"))
    time.sleep(1)
    print(colored("\t\t\t\t\t\t\t\t ███████████████    ██████████    ███████████████  ", "black","on_white"))
    time.sleep(1)
    print(colored("\t\t\t\t\t\t\t\t█████████████████  ████████████  █████████████████ ", "black","on_white"))
    time.sleep(1)
    print(colored("\t\t\t\t\t\t\t\t █████████████████ ████████████ █████████████████  ", "black","on_white"))
    print(colored("\t\t\t\t\t\t\t\t █████████████████ ████████████ █████████████████  ", "black","on_white"))
    print(colored("\t\t\t\t\t\t\t\t                                                   ", "black","on_white"))
    time.sleep(1)
    print(colored("\t\t\t\t\t\t\t\t    ██████████████████████████████████████████     ", "black","on_white"))
    print(colored("\t\t\t\t\t\t\t\t                                                   ", "black","on_white"))
    time.sleep(1)
    print(colored("\t\t\t\t\t\t\t\t       ████████████████████████████████████        ", "black","on_white"))
    print(colored("\t\t\t\t\t\t\t\t                                                   ", "black","on_white"))
    time.sleep(1)
    print(colored("\t\t\t\t\t\t\t\t           █████████ ████████ █████████            ", "black","on_white"))
    time.sleep(1)
    print(colored("\t\t\t\t\t\t\t\t               █████   ████   █████                ", "black","on_white"))
    print(colored("\t\t\t\t\t\t\t\t                 ███    ██    ███                  ", "black","on_white"))
    time.sleep(1)
    print(colored("\t\t\t\t\t\t\t\t                                                   ", "black","on_white"))
    time.sleep(1)
    print(colored("\t\t\t\t\t\t\t\t     █████  ██████  ██ ██████   █████   ██████     ", "black","on_white"))
    print(colored("\t\t\t\t\t\t\t\t    ██   ██ ██   ██ ██ ██   ██ ██   ██ ████        ", "black","on_white"))
    print(colored("\t\t\t\t\t\t\t\t    ███████ ██   ██ ██ ██   ██ ███████    ████     ", "black","on_white"))
    print(colored("\t\t\t\t\t\t\t\t    ██   ██ ██████  ██ ██████  ██   ██ ██████      ", "black","on_white"))
    print(colored("\t\t\t\t\t\t\t\t                                                   ", "black","on_white"))
    print(colored("\t\t\t\t\t\t\t\t                                                   ", "black","on_white"))
    

logo_adidas()
print()
cprint("\t\t\t\t\t\t\t\t\t =======PROGRAM TELAH SELESAI=======","green","on_white")